import { Lesson } from '../types';

export const phpLessonsPart1: Lesson[] = [
  {
    id: "php-home",
    title: {
      en: "PHP Home",
      km: "ទំព័រដើម PHP"
    },
    content: {
      en: `### Welcome to PHP Programming!
PHP (Hypertext Preprocessor) is a widely-used, open-source server-side scripting language designed specifically for web development. It is embedded directly within HTML, allowing developers to create highly dynamic and interactive websites.

### Why Learn PHP?
- **Popularity:** Powers over 75% of all websites on the internet, including major systems like WordPress, Wikipedia, and Facebook.
- **Easy Integration:** Blends perfectly with HTML, CSS, JavaScript, and various databases like MySQL and PostgreSQL.
- **Server-Side Execution:** Code is executed entirely on the server, sending only standard HTML to the client browser.
- **Massive Ecosystem:** Boasts an enormous community, comprehensive frameworks (Laravel, Symfony), and solid package support.

> **Tip:** You can write your script directly in our editor and click **Run Code** to execute it instantly in our backend environment.`,
      km: `### សូមស្វាគមន៍មកកាន់ការសិក្សាភាសា PHP!
PHP (Hypertext Preprocessor) គឺជាភាសាសរសេរកូដផ្នែកខាងម៉ាស៊ីនបម្រើ (Server-side) ដ៏ពេញនិយម និងបើកចំហ (Open-source) ដែលរចនាឡើងជាពិសេសសម្រាប់ការអភិវឌ្ឍគេហទំព័រ។ វាអាចបង្កប់ផ្ទាល់ជាមួយ HTML ដើម្បីបង្កើតវិបសាយដែលមានចលនាឌីណាមិក និងអន្តរកម្មខ្ពស់។

### ហេតុអ្វីត្រូវរៀន PHP?
- **ភាពពេញនិយម:** ដំណើរការជាង ៧៥% នៃគេហទំព័រទាំងអស់នៅលើអ៊ីនធឺណិត រួមទាំងប្រព័ន្ធធំៗដូចជា WordPress, Wikipedia, និង Facebook។
- **ងាយស្រួលសមាហរណកម្ម:** រួមបញ្ចូលគ្នាបានយ៉ាងល្អឥតខ្ចោះជាមួយ HTML, CSS, JavaScript និងប្រព័ន្ធទិន្នន័យ (MySQL, PostgreSQL)។
- **ការដំណើរការផ្នែកម៉ាស៊ីនបម្រើ:** កូដរត់ទាំងស្រុងនៅលើ server ហើយបញ្ជូនតែ HTML ធម្មតាមកកាន់កម្មវិធីរុករក (Browser)។
- **ប្រព័ន្ធអេកូឡូស៊ីដ៏ធំធេង:** មានសហគមន៍អ្នកប្រើប្រាស់ច្រើនលើសលប់ និងមាន Framework ខ្លាំងៗដូចជា Laravel និង Symfony។

> **អនុសាសន៍:** អ្នកអាចសរសេរកូដនៅក្នុងប្រអប់កូដខាងស្តាំ ហើយចុច **ដំណើរការកូដ (Run Code)** ដើម្បីសាកល្បងលទ្ធផលភ្លាមៗនៅលើម៉ាស៊ីនបម្រើរបស់យើង!`
    },
    starterCode: `<?php
echo "=== Welcome to Cambodian PHP Academy ===\\n";
echo "Start writing dynamic web servers in PHP today!\\n";
?>`
  },
  {
    id: "php-intro",
    title: {
      en: "PHP Intro",
      km: "សេចក្តីផ្តើម PHP"
    },
    content: {
      en: `### What is PHP?
Originally created by Rasmus Lerdorf in 1994, PHP stands for **Hypertext Preprocessor**.

### Key Characteristics:
- **Server-Side:** Runs on web servers (like Apache, Nginx, or IIS).
- **Embedded in HTML:** PHP code tags \`<?php ... ?>\` can be placed anywhere inside an HTML document.
- **Free & Multi-Platform:** Runs on Windows, Linux, macOS, and is free to download and use.

### What can PHP do?
1. Generate dynamic page content on-the-fly.
2. Create, open, read, write, and close files on the server.
3. Collect and process user data from forms.
4. Send and receive browser cookies and manage persistent sessions.
5. Control user access and encrypt sensitive data.`,
      km: `### តើ PHP ជាអ្វី?
PHP ត្រូវបានបង្កើតឡើងដំបូងដោយលោក Rasmus Lerdorf ក្នុងឆ្នាំ ១៩៩៤ ហើយបច្ចុប្បន្នជាពាក្យកាត់មកពី **Hypertext Preprocessor**។

### លក្ខណៈពិសេសៗ៖
- **ដំណើរការខាងម៉ាស៊ីនបម្រើ:** ដំណើរការនៅលើ Web Server (ដូចជា Apache, Nginx, ឬ IIS)។
- **បង្កប់ក្នុង HTML:** កូដ PHP ចាប់ផ្តើមដោយ \`<?php\` និងបញ្ចប់ដោយ \`?>\` ដែលអាចដាក់នៅកន្លែងណាក៏បានក្នុង HTML។
- **ឥតគិតថ្លៃ និងដំណើរការបានគ្រប់ប្រព័ន្ធ:** ដំណើរការលើ Windows, Linux, macOS ហើយអាចទាញយកមកប្រើដោយសេរី។

### តើ PHP អាចធ្វើអ្វីបានខ្លះ?
១. បង្កើតមាតិកាគេហទំព័រឌីណាមិកភ្លាមៗ។
២. បង្កើត បើក អាន សរសេរ និងបិទឯកសារនៅលើ Server។
៣. ប្រមូល និងដោះស្រាយទិន្នន័យដែលផ្ញើចេញពី Forms។
៤. ផ្ញើ និងទទួល Cookies ព្រមទាំងគ្រប់គ្រង Sessions សុវត្ថិភាព។
៥. គ្រប់គ្រងសិទ្ធិចូលប្រើប្រាស់របស់អ្នកប្រើប្រាស់ និងធ្វើកូដនីយកម្មទិន្នន័យសម្ងាត់។`
    },
    starterCode: `<?php
echo "PHP powers the dynamic web!\\n";
echo "This output was generated by executing PHP on the server.";
?>`
  },
  {
    id: "php-install",
    title: {
      en: "PHP Install",
      km: "ការដំឡើង PHP"
    },
    content: {
      en: `### Setting up PHP
To start building real applications locally on your computer, you need:
1. A local **Web Server** (usually Apache or Nginx).
2. **PHP** itself.
3. A **Database** (usually MySQL/MariaDB).

### Easy Package Installers:
For local development, downloading these bundles is highly recommended as they configure everything automatically:
- **XAMPP:** Supports Windows, Linux, and macOS. Includes Apache, MariaDB, and PHP.
- **MAMP:** Optimized for macOS but supports Windows too.
- **Laravel Herd:** An ultra-fast, zero-config local environment for macOS and Windows.

> **Note:** For this course, **everything is pre-installed in your browser sandbox!** You do not need to install anything locally to complete these exercises. Below, let's query our sandbox environment's PHP configuration.`,
      km: `### ការរៀបចំដំឡើង PHP
ដើម្បីចាប់ផ្តើមអភិវឌ្ឍកម្មវិធីពិតប្រាកដនៅលើកុំព្យូទ័ររបស់អ្នក អ្នកត្រូវការ៖
១. **Web Server** ក្នុងម៉ាស៊ីន (ភាគច្រើនប្រើ Apache ឬ Nginx)។
២. កម្មវិធីកម្មវិធីបកប្រែកូដ **PHP**។
៣. **ប្រព័ន្ធទិន្នន័យ (Database)** (ភាគច្រើនប្រើ MySQL)។

### កញ្ចប់កម្មវិធីដំឡើងងាយស្រួល៖
សម្រាប់ការអភិវឌ្ឍន៍នៅលើម៉ាស៊ីនផ្ទាល់ខ្លួន ការទាញយកកញ្ចប់កម្មវិធីទាំងនេះត្រូវបានណែនាំយ៉ាងខ្លាំង ព្រោះវាដំឡើងរាល់តម្រូវការទាំងអស់ស្វ័យប្រវត្តិ៖
- **XAMPP:** គាំទ្រលើ Windows, Linux, និង macOS។ រួមបញ្ចូលទាំង Apache, MariaDB, និង PHP។
- **MAMP:** ល្អបំផុតសម្រាប់ macOS ប៉ុន្តែក៏គាំទ្រ Windows ដែរ។
- **Laravel Herd:** បរិស្ថានអភិវឌ្ឍន៍លឿនបំផុត មិនបាច់កំណត់រចនាសម្ព័ន្ធ (Zero-config) សម្រាប់ macOS និង Windows។

> **ចំណាំ:** សម្រាប់វគ្គសិក្សានេះ **អ្វីៗគ្រប់យ៉ាងត្រូវបានដំឡើងជាស្រេចនៅក្នុងប្រអប់កូដរបស់អ្នក!** អ្នកមិនបាច់ដំឡើងអ្វីឡើយ។ ខាងក្រោមនេះ គឺកូដពិនិត្យមើលកំណែទម្រង់ (Configuration) នៃ PHP របស់យើង។`
    },
    starterCode: `<?php
echo "Current Sandbox PHP Version: " . PHP_VERSION . "\\n";
echo "OS running: " . PHP_OS . "\\n";
?>`
  },
  {
    id: "php-syntax",
    title: {
      en: "PHP Syntax",
      km: "រចនាសម្ព័ន្ធកូដ PHP"
    },
    content: {
      en: `### Basic PHP Syntax
A PHP script starts with \`<?php\` and ends with \`?>\`. Each line of code must terminate with a semicolon (\`;\`).

\`\`\`php
<?php
// PHP statement goes here
echo "Hello World";
?>
\`\`\`

### Case Sensitivity Rules:
- **Keywords, Functions, Classes:** Are **NOT** case-sensitive. \`ECHO\`, \`echo\`, and \`EcHo\` do the exact same thing.
- **Variables:** Are strictly **CASE-SENSITIVE**. \`$color\`, \`$COLOR\`, and \`$Color\` are treated as three completely distinct variables.

> **Pitfall:** Forgetting the semicolon (\`;\`) at the end of a line is one of the most common syntax errors for beginners, causing a compilation crash!`,
      km: `### រចនាសម្ព័ន្ធកូដ PHP ជាមូលដ្ឋាន
កូដ PHP ត្រូវចាប់ផ្តើមដោយ \`<?php\` និងបញ្ចប់ដោយ \`?>\`។ រាល់បន្ទាត់បញ្ជាកូដត្រូវបញ្ចប់ដោយសញ្ញាក្បៀសចំនុច (\`;\`)។

\`\`\`php
<?php
// បន្ទាត់បញ្ជាកូដនៅទីនេះ
echo "Hello World";
?>
\`\`\`

### ច្បាប់ប្រកាន់អក្សរតូចធំ (Case Sensitivity)៖
- **ពាក្យគន្លឹះ មុខងារ (Functions) និង Classes:** គឺ **មិន** ប្រកាន់អក្សរតូចធំឡើយ។ \`ECHO\`, \`echo\`, និង \`EcHo\` ដំណើរការដូចគ្នាទាំងអស់។
- **អថេរ (Variables):** គឺ **ប្រកាន់ខ្ជាប់** អក្សរតូចធំយ៉ាងតឹងរឹង។ \`$color\`, \`$COLOR\`, និង \`$Color\` គឺជាអថេរបីផ្សេងគ្នាទាំងស្រុង។

> **ប្រុងប្រយ័ត្ន:** ការភ្លេចដាក់សញ្ញាក្បៀសចំនុច (\`;\`) នៅចុងបញ្ចប់នៃបន្ទាត់កូដ គឺជាកំហុសទូទៅបំផុតសម្រាប់អ្នកចាប់ផ្តើមដំបូង ដែលធ្វើឱ្យកូដមិនដំណើរការ!`
    },
    starterCode: `<?php
// Keywords are NOT case-sensitive:
ECHO "Hello from ECHO!\\n";
echo "hello from echo!\\n";

// Variables ARE case-sensitive:
$color = "blue";
$COLOR = "red";

echo "The first color is: " . $color . "\\n";
echo "The second color is: " . $COLOR . "\\n";
?>`
  },
  {
    id: "php-comments",
    title: {
      en: "PHP Comments",
      km: "ការសរសេរមតិ Comments"
    },
    content: {
      en: `### Comments in PHP
Comments are lines in a script that are completely ignored by the PHP engine. They are used to explain code or temporarily disable parts of your program.

### PHP supports three types of comments:
1. **Single-line C-style:** Starts with \`//\`
2. **Single-line Shell-style:** Starts with \`#\`
3. **Multi-line block:** Starts with \`/*\` and ends with \`*/\`

\`\`\`php
<?php
// This is a single-line comment

# This is also a single-line comment

/*
  This is a multi-line comment block
  useful for documenting parameters.
*/
?>
\`\`\`

> **Note:** Good comments explain *why* something is written, not just *what* the line does.`,
      km: `### ការសរសេរមតិ (Comments) ក្នុង PHP
មតិ (Comments) គឺជាបន្ទាត់អត្ថបទដែលមិនត្រូវបានដំណើរការដោយម៉ាស៊ីនបកប្រែកូដ PHP ឡើយ។ គេប្រើវាដើម្បីពន្យល់ពីកូដ ឬបិទការដំណើរការកូដជាបណ្តោះអាសន្ន។

### PHP គាំទ្រការសរសេរមតិ ៣ ប្រភេទ៖
១. **មតិមួយបន្ទាត់ (C-style):** ចាប់ផ្តើមដោយ \`//\`
២. **មតិមួយបន្ទាត់ (Shell-style):** ចាប់ផ្តើមដោយ \`#\`
៣. **មតិច្រើនបន្ទាត់ (Multi-line block):** ចាប់ផ្តើមដោយ \`/*\` និងបញ្ចប់ដោយ \`*/\`

\`\`\`php
<?php
// នេះជាមតិមួយបន្ទាត់

# នេះក៏ជាមតិមួយបន្ទាត់ដែរ

/*
  នេះជាមតិច្រើនបន្ទាត់
  ងាយស្រួលសម្រាប់ការសរសេរពន្យល់វែងៗ។
*/
?>
\`\`\`

> **សម្គាល់:** ការសរសេរ Comments ល្អ គឺត្រូវពន្យល់ពីមូលហេតុ (Why) នៃកូដនោះ មិនមែនគ្រាន់តែបង្ហាញថាវាធ្វើអ្វី (What) នោះទេ។`
    },
    starterCode: `<?php
// 1. Single-line comment example
$x = 10; // We define variable x

# 2. Shell-style comment example
$y = 20; # We define variable y

/*
  3. Multi-line comment:
  Let's calculate the average
  of x and y.
*/
$average = ($x + $y) / 2;

echo "Average value is: " . $average . "\\n";
?>`
  },
  {
    id: "php-variables",
    title: {
      en: "PHP Variables",
      km: "អថេរ PHP"
    },
    content: {
      en: `### Declaring PHP Variables
In PHP, a variable always starts with the \`$\` sign, followed by the name of the variable.

### Variable Rules:
- Must start with a letter or an underscore (\`_\`).
- Cannot start with a number.
- Can only contain alphanumeric characters and underscores (\`A-z\`, \`0-9\`, \`_\`).
- Do not require explicit type declaration (PHP is loosely typed).

### Variable Scope:
PHP variables can be declared anywhere in the script. The scope defines where they can be accessed:
1. **Local:** Declared inside a function, accessible only within that function.
2. **Global:** Declared outside functions, accessible globally but requires the \`global\` keyword inside functions to modify.
3. **Static:** Declared inside a function but keeps its value when the function completes.`,
      km: `### ការប្រកាសអថេរ PHP
នៅក្នុង PHP អថេរតែងតែចាប់ផ្តើមដោយនិមិត្តសញ្ញា \`$\` រួចបន្តដោយឈ្មោះអថេរ។

### ច្បាប់បង្កើតឈ្មោះអថេរ៖
- ត្រូវតែចាប់ផ្តើមដោយអក្សរ ឬសញ្ញាខណ្ឌកណ្តាល (\`_\`)។
- មិនអាចចាប់ផ្តើមដោយលេខឡើយ។
- អាចមានតែតួអក្សរ លេខ និងសញ្ញាខណ្ឌកណ្តាល (\`A-z\`, \`0-9\`, \`_\`)។
- មិនបាច់កំណត់ប្រភេទទិន្នន័យជាមុនឡើយ (PHP is loosely typed)។

### Scope នៃអថេរ៖
អថេរអាចប្រកាសនៅទីណាក៏បាន។ Scope កំណត់ពីកន្លែងដែលអាចហៅអថេរនោះមកប្រើបាន៖
១. **Local Scope:** ប្រកាសក្នុងមុខងារ (Function) ហៅប្រើបានតែក្នុង Function នោះប៉ុណ្ណោះ។
២. **Global Scope:** ប្រកាសនៅក្រៅ Function ហៅប្រើបានទូទៅ ប៉ុន្តែបើចង់ប្រើក្នុង Function ត្រូវប្រើពាក្យគន្លឹះ \`global\`។
៣. **Static Scope:** ប្រកាសក្នុង Function ប៉ុន្តែរក្សាតម្លៃដដែលទោះជា Function រត់ចប់ក៏ដោយ។`
    },
    starterCode: `<?php
$globalVar = 100;

function testScope() {
    // To access global variable, use 'global' keyword
    global $globalVar;
    $localVar = 5;
    
    static $counter = 0; // keeps value
    $counter++;
    
    echo "Global inside: " . $globalVar . "\\n";
    echo "Local inside: " . $localVar . "\\n";
    echo "Static counter: " . $counter . "\\n";
}

testScope();
testScope();
?>`
  },
  {
    id: "php-echo-print",
    title: {
      en: "PHP Echo / Print",
      km: "កំហុស Echo / Print"
    },
    content: {
      en: `### Outputting Data: echo vs print
Both \`echo\` and \`print\` are language constructs (not actual functions, so parentheses are optional) used to display data on screen.

### Major Differences:
- **echo:**
  - Has no return value.
  - Can take multiple arguments separated by commas (e.g., \`echo "a", "b", "c"\`).
  - Marginally faster than \`print\`.
- **print:**
  - Has a return value of \`1\` (allowing it to be used in expressions).
  - Can only take a single argument.

> **Tip:** Double quotes (\`"\`) evaluate variables and escape codes like \`\\n\`, while single quotes (\`'\`) output the literal string exactly as written.`,
      km: `### ការបង្ហាញទិន្នន័យ៖ echo និង print
ទាំង \`echo\` និង \`print\` គឺជាសំណង់ភាសា (Language constructs - មិនមែនជាមុខងារពិតប្រាកដទេ ដូច្នេះមិនបាច់ប្រើវង់ក្រចកក៏បាន) សម្រាប់បង្ហាញទិន្នន័យនៅលើអេក្រង់។

### ភាពខុសគ្នាសំខាន់ៗ៖
- **echo:**
  - គ្មានតម្លៃត្រឡប់មកវិញ (No return value)។
  - អាចទទួលយកអាគុយម៉ង់ច្រើនដោយប្រើសញ្ញាក្បៀស (ឧទាហរណ៍៖ \`echo "a", "b", "c"\`)។
  - លឿនជាង \`print\` បន្តិចបន្តួច។
- **print:**
  - មានតម្លៃត្រឡប់មកវិញស្មើនឹង \`1\` (អាចយកទៅប្រើក្នុងកន្សោមលក្ខខណ្ឌបាន)។
  - អាចទទួលយកអាគុយម៉ង់បានតែមួយគត់។

> **គន្លឹះ:** របាំងស្ទួន (\`"\`) នឹងបំប្លែងតម្លៃអថេរ និងកូដបញ្ជាដូចជា \`\\n\` រីឯរបាំងទោល (\`'\`) នឹងបង្ហាញអក្សរចំៗតាមអ្វីដែលបានសរសេរ។`
    },
    starterCode: `<?php
$name = "Dara";

// Double quotes parse variables
echo "My name is $name with echo!\\n";

// Single quotes do NOT parse variables
echo 'My name is $name with echo!\\n' . "\\n";

// echo multiple parameters
echo "Hello ", "Cambodia ", "Land of Angkor!\\n";

// print returns 1
$status = print "Printing message...\\n";
echo "Print status: " . $status . "\\n";
?>`
  },
  {
    id: "php-data-types",
    title: {
      en: "PHP Data Types",
      km: "ប្រភេទទិន្នន័យ PHP"
    },
    content: {
      en: `### PHP Data Types
Variables can store data of different types, and different data types can do different things.

### PHP supports the following data types:
1. **String:** Sequence of characters (e.g., \`"Hello"\`).
2. **Integer:** Non-decimal whole numbers between min/max bounds (e.g., \`512\`).
3. **Float (double):** Decimal numbers (e.g., \`10.5\`).
4. **Boolean:** True or false values (\`true\`, \`false\`).
5. **Array:** Stores multiple values in a single variable.
6. **Object:** Instance of a programmer-defined class.
7. **NULL:** Represents a variable with no value assigned.
8. **Resource:** Reference to external server resources (e.g., databases, file streams).

> **Tip:** Use the built-in \`var_dump()\` function to output both the data type and value of an object or variable!`,
      km: `### ប្រភេទទិន្នន័យរបស់ PHP
អថេរអាចរក្សាទុកប្រភេទទិន្នន័យផ្សេងៗគ្នា ហើយប្រភេទទិន្នន័យខុសគ្នានឹងធ្វើសកម្មភាពផ្សេងៗគ្នា។

### PHP គាំទ្រប្រភេទទិន្នន័យដូចខាងក្រោម៖
១. **String:** សំណុំតួអក្សរ (ឧទាហរណ៍៖ \`"Hello"\`)។
២. **Integer:** ចំនួនគត់គ្មានក្បៀស (ឧទាហរណ៍៖ \`512\`)។
៣. **Float (double):** ចំនួនទសភាគមានក្បៀស (ឧទាហរណ៍៖ \`10.5\`)។
៤. **Boolean:** តម្លៃពិត ឬមិនពិត (\`true\`, \`false\`)។
៥. **Array:** រក្សាទុកតម្លៃច្រើនក្នុងអថេរតែមួយ។
៦. **Object:** ធាតុពិតដែលបង្កើតចេញពី Class។
៧. **NULL:** តំណាងឱ្យអថេរដែលគ្មានតម្លៃ។
៨. **Resource:** តំណាងឱ្យធនធានខាងក្រៅ (ឧទាហរណ៍៖ ឯកសារ ការភ្ជាប់ប្រព័ន្ធទិន្នន័យ)។

> **អនុសាសន៍:** ប្រើមុខងារ \`var_dump()\` ដើម្បីបង្ហាញទាំងប្រភេទទិន្នន័យ និងតម្លៃរបស់អថេរភ្លាមៗ!`
    },
    starterCode: `<?php
$str = "Angkor Wat";
$int = 1181;
$float = 99.95;
$bool = true;
$arr = array("Phnom Penh", "Siem Reap", "Battambang");
$nullVal = NULL;

var_dump($str);
var_dump($int);
var_dump($float);
var_dump($bool);
var_dump($arr);
var_dump($nullVal);
?>`
  },
  {
    id: "php-strings",
    title: {
      en: "PHP Strings",
      km: "ខ្សែអក្សរ Strings"
    },
    content: {
      en: `### PHP String Operations
A string is a sequence of characters, like "Hello world!". PHP provides powerful built-in functions for manipulating strings.

### Key Built-in String Functions:
- \`strlen($str)\`: Returns the length of the string.
- \`str_word_count($str)\`: Counts the number of words.
- \`strrev($str)\`: Reverses the characters.
- \`strpos($str, $search)\`: Returns the byte position of the first match, or \`false\`.
- \`str_replace($search, $replace, $str)\`: Replaces text occurrences.
- \`strtolower($str)\` / \`strtoupper($str)\`: Changes capitalization.

> **Pitfall:** PHP counts positions starting from index \`0\`, not \`1\`!`,
      km: `### ប្រតិបត្តិការខ្សែអក្សរ (Strings) ក្នុង PHP
ខ្សែអក្សរ គឺជាលំដាប់នៃតួអក្សរ ដូចជា "Hello world!"។ PHP ផ្តល់នូវមុខងារស្រាប់ (Built-in functions) ដ៏មានឥទ្ធិពលសម្រាប់កែច្នៃខ្សែអក្សរ។

### មុខងារសំខាន់ៗ៖
- \`strlen($str)\`: ស្វែងរកប្រវែងខ្សែអក្សរ (ចំនួនតួអក្សរ)។
- \`str_word_count($str)\`: រាប់ចំនួនពាក្យក្នុងអក្សរ។
- \`strrev($str)\`: ត្រឡប់អក្សរពីក្រោយមកមុខវិញ។
- \`strpos($str, $search)\`: ស្វែងរកទីតាំងដំបូងនៃពាក្យដែលចង់រក (បើរកមិនឃើញនឹងផ្តល់តម្លៃ \`false\`)។
- \`str_replace($search, $replace, $str)\`: ជំនួសពាក្យចាស់ដោយពាក្យថ្មី។
- \`strtolower($str)\` / \`strtoupper($str)\`: បំប្លែងជាអក្សរតូច ឬអក្សរធំ។

> **សម្គាល់:** PHP ចាប់ផ្តើមរាប់ទីតាំង (Index) ចេញពីលេខ \`0\` មិនមែនលេខ \`1\` ឡើយ!`
    },
    starterCode: `<?php
$text = "Learn PHP in Cambodia!";

echo "String: " . $text . "\\n";
echo "Length: " . strlen($text) . " bytes\\n";
echo "Word Count: " . str_word_count($text) . "\\n";
echo "Reversed: " . strrev($text) . "\\n";
echo "Position of 'PHP': " . strpos($text, "PHP") . "\\n";
echo "Replace 'Cambodia' with 'World': " . str_replace("Cambodia", "World", $text) . "\\n";
?>`
  },
  {
    id: "php-numbers",
    title: {
      en: "PHP Numbers",
      km: "លេខ និងចំនួន Numbers"
    },
    content: {
      en: `### PHP Numeric Management
PHP handles integers and floats dynamically, converting data representation when operations cross domains.

### Basic Check Functions:
- \`is_int($x)\` / \`is_integer($x)\`: Checks if value is an integer.
- \`is_float($x)\` / \`is_double($x)\`: Checks if value is a float.
- \`is_nan($x)\`: Checks if value is "Not a Number" (invalid mathematical outputs).
- \`is_numeric($x)\`: Checks if value can be safely parsed as a numeric digit or string.

> **Pitfall:** Be careful when comparing strings and numbers directly! Since PHP tries to auto-cast, \`"10" == 10\` is true, but \`"10" === 10\` is false.`,
      km: `### ការគ្រប់គ្រងទិន្នន័យលេខក្នុង PHP
PHP គ្រប់គ្រងចំនួនគត់ (Integers) និងទសភាគ (Floats) ដោយស្វ័យប្រវត្តិ និងបំប្លែងទិន្នន័យភ្លាមៗនៅពេលដំណើរការគណនា។

### មុខងារត្រួតពិនិត្យមូលដ្ឋាន៖
- \`is_int($x)\` / \`is_integer($x)\`: ពិនិត្យមើលថាតើវាជាចំនួនគត់មែនឬទេ។
- \`is_float($x)\` / \`is_double($x)\`: ពិនិត្យមើលថាតើវាជាចំនួនទសភាគមែនឬទេ។
- \`is_nan($x)\`: ពិនិត្យមើលថាតើតម្លៃគណនាមិនត្រឹមត្រូវតាមលក្ខណៈគណិតវិទ្យា (Not a Number) មែនឬទេ។
- \`is_numeric($x)\`: ពិនិត្យមើលថាតើអថេរនោះជាលេខ ឬខ្សែអក្សរតំណាងលេខដែលអាចបំប្លែងបានដែរឬទេ។

> **ចំណាំ:** ត្រូវប្រុងប្រយ័ត្នពេលប្រៀបធៀបអត្ថបទលេខ និងលេខផ្ទាល់! ដោយសារ PHP ធ្វើការ Auto-cast ដូច្នេះ \`"10" == 10\` គឺពិត (true) ប៉ុន្តែ \`"10" === 10\` គឺមិនពិតឡើយ (false)។`
    },
    starterCode: `<?php
$a = 455;
$b = 12.34;
$c = "123.45";

echo "Is \$a integer? " . (is_int($a) ? "Yes" : "No") . "\\n";
echo "Is \$b float? " . (is_float($b) ? "Yes" : "No") . "\\n";
echo "Is \$c numeric? " . (is_numeric($c) ? "Yes" : "No") . "\\n";

// NaN Test
$nanValue = acos(8);
echo "Is acos(8) NaN? " . (is_nan($nanValue) ? "Yes" : "No") . "\\n";
?>`
  },
  {
    id: "php-casting",
    title: {
      en: "PHP Casting",
      km: "ការបំប្លែងប្រភេទ Casting"
    },
    content: {
      en: `### Explicit Type Casting
Type casting allows you to manually force a variable to change to a specific data type.

### Supported PHP Casts:
- \`(string)\` - Casts to String
- \`(int)\` / \`(integer)\` - Casts to Integer
- \`(float)\` / \`(double)\` / \`(real)\` - Casts to Float
- \`(bool)\` / \`(boolean)\` - Casts to Boolean
- \`(array)\` - Casts to Array
- \`(object)\` - Casts to Object

\`\`\`php
$floatVal = 5.99;
$intVal = (int)$floatVal; // truncates decimal portion -> 5
\`\`\`

> **Note:** Casting a decimal float to an integer will simply discard the decimal portion, not round the value.`,
      km: `### ការកំណត់បំប្លែងប្រភេទដោយផ្ទាល់ (Explicit Casting)
Type Casting អនុញ្ញាតឱ្យអ្នកបង្ខំអថេរមួយឱ្យប្តូរទៅជាប្រភេទទិន្នន័យជាក់លាក់ណាមួយដោយដៃ។

### ប្រភេទ Casting ដែល PHP គាំទ្រ៖
- \`(string)\` - បំប្លែងទៅជាខ្សែអក្សរ String
- \`(int)\` / \`(integer)\` - បំប្លែងទៅជាចំនួនគត់ Integer
- \`(float)\` / \`(double)\` - បំប្លែងទៅជាចំនួនទសភាគ Float
- \`(bool)\` / \`(boolean)\` - បំប្លែងទៅជាតម្លៃប៊ូលីន Boolean
- \`(array)\` - បំប្លែងទៅជាអារេ Array
- \`(object)\` - បំប្លែងទៅជាវត្ថុ Object

\`\`\`php
$floatVal = 5.99;
$intVal = (int)$floatVal; // កាត់កន្ទុយទសភាគចោល -> 5
\`\`\`

> **សម្គាល់:** ការបំប្លែងចំនួនទសភាគទៅជាចំនួនគត់នឹងលុបផ្នែកខាងក្រោយក្បៀសចោលទាំងស្រុង ដោយមិនធ្វើការបង្គត់ឡើងឡើយ។`
    },
    starterCode: `<?php
$strNumber = "42";
$floatVal = 18.75;
$boolTrue = 1;
$nullVal = null;

// Perform Casting
$intResult = (int)$strNumber;
$truncatedInt = (int)$floatVal;
$booleanResult = (bool)$boolTrue;
$arrayResult = (array)$floatVal;

var_dump($intResult);
var_dump($truncatedInt);
var_dump($booleanResult);
var_dump($arrayResult);
?>`
  },
  {
    id: "php-math",
    title: {
      en: "PHP Math",
      km: "គណិតវិទ្យា PHP Math"
    },
    content: {
      en: `### Built-in PHP Math Functions
PHP features robust built-in mathematical functions that let you calculate values on the fly without needing external math libraries.

### Common Functions:
- \`pi()\`: Returns value of PI (approx. 3.14159...).
- \`min($args)\` / \`max($args)\`: Finds lowest or highest number in a series or array.
- \`abs($x)\`: Absolute (positive) value of a number.
- \`sqrt($x)\`: Calculates square root of a number.
- \`round($x)\`: Rounds floating-point values to nearest integer.
- \`rand($min, $max)\`: Generates a random integer within a range.

> **Tip:** Use \`random_int($min, $max)\` instead of \`rand()\` for secure random values like password generation, since \`random_int()\` is cryptographically secure.`,
      km: `### មុខងារគណិតវិទ្យា PHP Math
PHP រួមបញ្ចូលមុខងារគណិតវិទ្យាស្រាប់ៗយ៉ាងសំបូរបែប ដែលអនុញ្ញាតឱ្យអ្នកគណនាតម្លៃភ្លាមៗដោយមិនបាច់ប្រើបណ្ណាល័យខាងក្រៅឡើយ។

### មុខងារដែលប្រើញឹកញាប់៖
- \`pi()\`: ផ្តល់តម្លៃរបស់លេខ ផាយ (៣.១៤១៥៩...)។
- \`min($args)\` / \`max($args)\`: ស្វែងរកតម្លៃតូចបំផុត ឬធំបំផុតក្នុងចំណោមទិន្នន័យ។
- \`abs($x)\`: គណនាតម្លៃដាច់ខាត (តែងតែវិជ្ជមាន)។
- \`sqrt($x)\`: គណនាឫសការ៉េនៃចំនួនមួយ។
- \`round($x)\`: បង្គត់ចំនួនទសភាគទៅជាចំនួនគត់ដែលនៅជិតបំផុត។
- \`rand($min, $max)\`: បង្កើតលេខចៃដន្យ (Random) ក្នុងចន្លោះជាក់លាក់។

> **គន្លឹះ:** ប្រើប្រាស់ \`random_int($min, $max)\` ជំនួសឱ្យ \`rand()\` សម្រាប់ការបង្កើតតម្លៃចៃដន្យដែលមានសុវត្ថិភាពខ្ពស់ (ដូចជាការបង្កើតលេខកូដសម្ងាត់) ព្រោះវាការពារការទាយដឹង។`
    },
    starterCode: `<?php
echo "PI Value: " . pi() . "\\n";
echo "Minimum of (0, 150, -30, 20): " . min(0, 150, -30, 20) . "\\n";
echo "Maximum of (0, 150, -30, 20): " . max(0, 150, -30, 20) . "\\n";
echo "Square Root of 81: " . sqrt(81) . "\\n";
echo "Round 6.4: " . round(6.4) . " | Round 6.6: " . round(6.6) . "\\n";
echo "Random Number between 10 and 50: " . rand(10, 50) . "\\n";
?>`
  },
  {
    id: "php-constants",
    title: {
      en: "PHP Constants",
      km: "ថេរ Constants"
    },
    content: {
      en: `### PHP Global Constants
A constant is an identifier (name) for a simple value that cannot be altered or undefined during script execution. Unlike variables, constants automatically have global scope.

### Creating a Constant:
1. **Using \`define()\`:**
   - Parameter 1: Name of the constant (usually uppercase).
   - Parameter 2: Value.
   - Can be defined inside loops or conditional blocks.
2. **Using the \`const\` keyword:**
   - Declared at outer script scope or inside class models.
   - Faster at compile-time but cannot be placed in local blocks or functions.

> **Pitfall:** Suffixing constants with a \`$\` is wrong. You access a constant simply by using its raw name without any preceding character (e.g., \`SITE_URL\`, not \`$SITE_URL\`).`,
      km: `### អថេរថេរ (Global Constants) ក្នុង PHP
ថេរ (Constant) គឺជាឈ្មោះសម្គាល់តម្លៃសាមញ្ញមួយដែលមិនអាចកែប្រែ ឬលុបចោលបានឡើយ ក្នុងកំឡុងពេលដំណើរការកម្មវិធី។ ខុសពីអថេរធម្មតា ថេរមានដែនសមត្ថកិច្ចសកល (Global Scope) ស្វ័យប្រវត្តិ។

### ការបង្កើតថេរ៖
១. **ប្រើប្រាស់ \`define()\`:**
   - អាគុយម៉ង់ទី១៖ ឈ្មោះរបស់ថេរ (ជាទូទៅសរសេរជាអក្សរធំ)។
   - អាគុយម៉ង់ទី២៖ តម្លៃរបស់ថេរ។
   - អាចបង្កើតនៅក្នុងលក្ខខណ្ឌ ឬរង្វិលជុំបាន។
២. **ប្រើប្រាស់ពាក្យគន្លឹះ \`const\`:**
   - ប្រកាសនៅខាងក្រៅកូដ ឬក្នុង Class។
   - លឿនជាងពេល compile ប៉ុន្តែមិនអាចដាក់ក្នុង Function ឬលក្ខខណ្ឌឡើយ។

> **ប្រុងប្រយ័ត្ន:** ការដាក់សញ្ញា \`$\` ពីមុខថេរគឺខុសច្បាប់។ អ្នកត្រូវហៅប្រើវាដោយផ្ទាល់តាមរយៈឈ្មោះរបស់វា (ឧទាហរណ៍៖ \`SITE_URL\` មិនមែន \`$SITE_URL\` ឡើយ)។`
    },
    starterCode: `<?php
// Define constants
define("WEBSITE_NAME", "Angkor Academy");
const API_KEY = "xyz_987654321";

echo "Welcome to " . WEBSITE_NAME . "\\n";
echo "API Key used is: " . API_KEY . "\\n";

// Constants have global scope automatically
function testConstantScope() {
    echo "Accessing constant inside function: " . WEBSITE_NAME . "\\n";
}

testConstantScope();
?>`
  },
  {
    id: "php-magic-constants",
    title: {
      en: "PHP Magic Constants",
      km: "ថេរមន្តអាគម Magic Constants"
    },
    content: {
      en: `### Predefined Magic Constants
PHP offers nine special predefined constants called **Magic Constants** that resolve to different values depending on where they are executed. They are characterized by starting and ending with two underscores (\`__\`).

### Important Magic Constants:
- \`__LINE__\`: The current line number of the script.
- \`__FILE__\`: The full path and filename of the active file.
- \`__DIR__\`: The absolute directory path of the active file.
- \`__FUNCTION__\`: The active function name.
- \`__CLASS__\`: The active class name (includes namespace).
- \`__METHOD__\`: The active class method name.
- \`__NAMESPACE__\`: The name of the active namespace.`,
      km: `### Magic Constants របស់ PHP
PHP ផ្តល់ជូនថេរសម្ងាត់ចំនួន ៩ ដែលហៅថា **Magic Constants** ដែលមានតម្លៃប្រែប្រួលទៅតាមទីតាំងដែលវារត់ក្នុងកូដ។ ពួកវាត្រូវបានសម្គាល់ដោយសញ្ញាខណ្ឌកណ្តាលពីរ (\`__\`) នៅខាងមុខ និងខាងក្រោយ។

### Magic Constants សំខាន់ៗ៖
- \`__LINE__\`: បង្ហាញលេខបន្ទាត់កូដបច្ចុប្បន្ន។
- \`__FILE__\`: បង្ហាញផ្លូវទីតាំងពេញលេញ និងឈ្មោះឯកសារដែលកំពុងរត់។
- \`__DIR__\`: បង្ហាញតែក្លឹបថតឯកសារ (Directory) របស់ឯកសារនោះ។
- \`__FUNCTION__\`: បង្ហាញឈ្មោះមុខងារ Function ដែលកំពុងរត់។
- \`__CLASS__\`: បង្ហាញឈ្មោះ Class ដែលកំពុងប្រើ។
- \`__METHOD__\`: បង្ហាញឈ្មោះ Method របស់ Class។
- \`__NAMESPACE__\`: បង្ហាញឈ្មោះ Namespace បច្ចុប្បន្ន។`
    },
    starterCode: `<?php
echo "Current Line: " . __LINE__ . "\\n";
echo "Current File Location: " . __FILE__ . "\\n";
echo "Current Directory: " . __DIR__ . "\\n";

function myAwesomeFunction() {
    echo "Running inside function: " . __FUNCTION__ . "\\n";
}

myAwesomeFunction();
?>`
  },
  {
    id: "php-operators",
    title: {
      en: "PHP Operators",
      km: "ប្រមាណសញ្ញា Operators"
    },
    content: {
      en: `### PHP Operators
Operators are symbols used to perform computational actions on variables and values.

### Categories of Operators:
1. **Arithmetic:** \`+\`, \`-\`, \`*\`, \`/\`, \`%\` (Modulo), \`**\` (Exponentiation).
2. **Assignment:** \`=\`, \`+=\`, \`-=\`, \`*=\`, \`/=\`.
3. **Comparison:** 
   - \`==\` (Equal) / \`===\` (Identical - value & type).
   - \`<>\` or \`!=\` (Not equal).
   - \`<=>\` (Spaceship operator): Returns \`-1\` if left is smaller, \`0\` if equal, \`1\` if larger.
4. **Logical:** \`&&\` (And), \`||\` (Or), \`!\` (Not), \`and\`, \`or\`, \`xor\`.
5. **String Concatenation:** \`.\` (Dot - joins two strings), \`.=\` (Appends).`,
      km: `### ប្រមាណសញ្ញា (Operators) ក្នុង PHP
Operators គឺជានិមិត្តសញ្ញាដែលប្រើដើម្បីអនុវត្តការគណនាផ្សេងៗលើតម្លៃ និងអថេរ។

### ប្រភេទប្រមាណសញ្ញាសំខាន់ៗ៖
១. **គណិតវិទ្យា (Arithmetic):** \`+\`, \`-\`, \`*\`, \`/\`, \`%\` (Modulo-ចែករកសំណល់), \`**\` (Exponentiation-ស្វ័យគុណ)។
២. **ផ្តល់តម្លៃ (Assignment):** \`=\`, \`+=\`, \`-=\`, \`*=\`, \`/=\`។
៣. **ប្រៀបធៀប (Comparison):**
   - \`==\` (ស្មើ) / \`===\` (ដូចគ្នាទាំងស្រុង - ទាំងតម្លៃ និងប្រភេទ)។
   - \`<>\` ឬ \`!=\` (មិនស្មើ)។
   - \`<=>\` (Spaceship operator): ផ្តល់តម្លៃ \`-1\` បើខាងឆ្វេងតូចជាង, \`0\` បើស្មើ, \`1\` បើខាងឆ្វេងធំជាង។
៤. **តក្កវិទ្យា (Logical):** \`&&\` (និង), \`||\` (ឬ), \`!\` (មិន)។
៥. **ភ្ជាប់អត្ថបទ (String Concatenation):** \`.\` (សញ្ញាចុច - ប្រើសម្រាប់តភ្ជាប់អក្សរពីរ), \`.=\` (បន្ថែមអក្សរបន្ត)។`
    },
    starterCode: `<?php
$x = 10;
$y = 3;

echo "Modulo ($x % $y) = " . ($x % $y) . "\\n";
echo "Exponentiation ($x ** $y) = " . ($x ** $y) . "\\n";

// Spaceship comparisons
echo "5 <=> 10 returns: " . (5 <=> 10) . " (left is smaller)\\n";
echo "10 <=> 10 returns: " . (10 <=> 10) . " (equal)\\n";
echo "15 <=> 10 returns: " . (15 <=> 10) . " (left is larger)\\n";

// String concatenation
$msg = "Hello";
$msg .= " Cambodia!";
echo "Combined string: " . $msg . "\\n";
?>`
  }
];
